name: payment_method
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  toastification: ^2.3.0
  get: ^4.6.6
  shared_preferences: ^2.4.0
  hugeicons: ^0.0.7
  google_fonts: ^6.2.1
  lottie: ^3.3.1
  http: ^1.3.0
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/Image/
